### ISSUE TITLE
Getting Errors when iported (2017.4.1)

### ISSUE THREAD

**Issue by gl33mer** [tchpowdog/SurrealGrassShader#1]
These errors:

Assets/SurrealGrassShader/SurrealGrassCreator.cs(100,41): error CS1502: The best overloaded method match for `UnityEditor.EditorGUILayout.Popup(UnityEngine.GUIContent, int, UnityEngine.GUIContent[], params UnityEngine.GUILayoutOption[])' has some invalid arguments

Assets/SurrealGrassShader/SurrealGrassCreator.cs(100,96): error CS1503: Argument `#3' cannot convert `string[]' expression to type `UnityEngine.GUIContent[]'

**Comment by tchpowdog** [comment]
I think this is a Unity bug.  I'll take a look when I get the chance.  Posting issues here is cool but I do not get the alerts for it.  It's probably better to post issues in the Unity forum.  I will get alerts for those.

**Comment by gl33mer** [comment]
Cool :-) thanks.

**Comment by tchpowdog** [comment]
this should be fixed now, pull down the SurrealGrassCreator.cs file and try it out.

**Comment by gl33mer** [comment]
Ok. Those errors are gone. (I'll open an issue with my current situation)
